language: node_js
before_script:
  - npm install -g gatsby-cli
  - yum install wget autoconf automake gcc nasm libtool
node_js:
  - "12.12.0"
deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: cd ./ && yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master
